[2020-04-28 18:27:10,738] {alignmentservice.py:242} MainThread INFO in alignmentservice: Consumer running.......
[2020-04-28 18:28:37,761] {alignmentservice.py:243} MainThread INFO in alignmentservice: Consumer running.......
[2020-04-28 18:35:00,032] {alignmentservice.py:252} MainThread INFO in alignmentservice: Consumer running.......
[2020-04-28 18:45:51,961] {consumer.py:252} MainThread INFO in consumer: Consumer running.......
[2020-04-28 19:14:59,527] {consumer.py:33} MainThread INFO in consumer: Consumer running.......
[2020-05-08 13:42:25,392] {consumer.py:35} MainThread INFO in consumer: Consumer running.......
[2020-05-08 13:52:36,359] {consumer.py:39} MainThread INFO in consumer: Consuming from the Kafka Queue......
[2020-05-08 13:54:41,090] {alignmentservice.py:50} MainThread INFO in alignmentservice: Alignment process starts for job: 15889250265440123
[2020-05-08 13:54:41,101] {consumer.py:44} MainThread ERROR in consumer: Exception while consuming: can only concatenate str (not "dict") to str
[2020-05-08 13:54:41,121] {consumer.py:45} MainThread ERROR in consumer: None
[2020-06-18 12:33:40,850] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
[2020-06-24 14:55:10,979] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 14:57:09,083] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 14:57:49,924] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 14:59:01,687] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:00:13,954] {app.py:29} MainThread INFO in app: Starting
[2020-06-24 15:00:13,955] {alignmentconsumer.py:40} AlignerKafka-Thread INFO in alignmentconsumer: Consumer
[2020-06-24 15:00:14,807] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:02:29,647] {app.py:29} MainThread INFO in app: Starting
[2020-06-24 15:02:30,511] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:03:25,030] {app.py:29} MainThread INFO in app: Starting
[2020-06-24 15:03:25,035] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-06-24 15:03:25,883] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:04:38,075] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:04:55,103] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-06-24 15:05:33,022] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-06-24 15:05:56,558] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-07-01 13:08:59,444] {alignmentconsumer.py:42} AlignerKafka-Thread INFO in alignmentconsumer: Consumer running.......
[2020-07-01 13:09:00,461] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-03 17:43:22,555] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
[2020-07-07 18:10:35,050] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-07 19:22:45,915] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:14:17,627] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:43:58,379] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:44:13,523] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:53:00,436] {sentenceconsumer.py:43} SentenceKafka-Thread INFO in sentenceconsumer: Consumer running.......
[2020-07-08 17:53:00,441] {_internal.py:122} MainThread INFO in _internal:  * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
[2020-07-08 17:53:19,456] {_internal.py:122} Thread-1 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:53:19] "[33mGET / HTTP/1.1[0m" 404 -
[2020-07-08 17:53:20,110] {_internal.py:122} Thread-2 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:53:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2020-07-08 17:53:30,232] {_internal.py:122} Thread-3 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:53:30] "[33mGET / HTTP/1.1[0m" 404 -
[2020-07-08 17:54:54,699] {app.py:1891} Thread-4 ERROR in app: Exception on /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines [POST]
Traceback (most recent call last):
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/controller/sentencecontroller.py", line 32, in createalignmentwflowjob
    return service.wf_process(data)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 49, in wf_process
    self.update_job_details(object_in, True)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/service/sentenceservice.py", line 56, in update_job_details
    repo.create_job(object_in)
  File "/home/dhiraj/Documents/Anuwad/anuvaad/anuvaad-etl/anuvaad-extractor/ocr/etl-sentence/repository/sentencerepository.py", line 24, in create_job
    col.insert_one(object_in)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
    s = self._ensure_session(session)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/home/dhiraj/python_env/Anuvaad/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[2020-07-08 17:54:54,722] {_internal.py:122} Thread-4 INFO in _internal: 127.0.0.1 - - [08/Jul/2020 17:54:54] "[1m[35mPOST /anuvaad-etl/extractor/sentence/v1/sentences/extract_lines HTTP/1.1[0m" 500 -
